let signo = prompt('¿Cual es tu signo?')

switch (signo) {
  case 'aries':
  case 'Aries':
    console.log('Esta semana tu concentración puede verse afectada por falta de descanso o por una mala alimentación, Aries. Esto puede influir en tu trabajo, a sí que haz lo posible para recuperar tu energía y tu poder mental. En el terreno económico tendrás que tomar alguna decisión importante. No corras, tómate tu tiempo, tu dinero está en riesgo. En el campo laboral, esta semana habrán algunas complicaciones. Las superarás si sigues firme en tus convicciones y en tu código ético. Sé tú misma y no te bajes del burro por mucho que te presionen. Ahora tienes que confiar más que nunca en tus propias capacidades y en tu intuición, que estos días está a tope, aunque todos crean que estás equivocada. El tiempo te dará la razón y no tardará mucho en hacerlo. Si algún amigo o amiga te viene con el cuento de que controles a tu pareja e insinúa que puede haber infidelidad, ponlo en cuarentena. Al amigo y a sus sospechas. La envidia es muy mala.')
    break
  case 'tauro':
  case 'Tauro':
    console.log('En estos momentos estás pletórica, nativa de Tauro. Tienes energía para dar y vender. Además has superado la etapa de bajón que atravesabas y se nota en tu actitud, por eso alguien puede ofrecerte que participes en un proyecto comercial que es una golosina. Pero no te conviene aceptar ahora mismo, no tienes bien aspectado el asunto de los negocios. Ten cautela y no te precipites en la respuesta. Aplázala por unos días, porque podrías poner tu situación económica en riesgo. De momento sigue como estás y dedícate a resolver asuntos pendientes y a concretar compromisos que ibas posponiendo. Finaliza todo lo que esté empezado. Esta energía que sientes te hace venir ganas de mucha actividad física, es fantástico pero no te pases o puedes tener agujetas y dolores musculares. Ya sabes, es mejor poco esfuerzo y mucha constancia. Es también un buen momento para el amor. En tu pareja hay todo lo que puedes pedir, ternura, comprensión y pasión. Te ha costado, pero parece que al fin lo has conseguido.')
    break
  case 'geminis':
    case 'Geminis':
    console.log('Se avecinan cambios en el terreno laboral y no negativos precisamente, afortunada Géminis, aunque tendrás que poner mucha atención porque alguien podría querer perjudicarte. En tu empresa puede haber una reestructuración y tus superiores te tienen en cuenta por tu capacidad de trabajo y tu experiencia. Te valoran mucho y esto repercutirá también en tus ingresos. Un ascenso está en el aire. Sin embargo, ahí está la parte menos buena. Quizá se trate de sustituir a alguno de tus jefes con el que tuviste muchas peloteras. Ahora estarías en situación de cobrarte los malos ratos que te hizo pasar, pero no lo hagas o te crearás un enemigo muy peligroso. Concéntrate en tu trabajo y deja que te resbale todo lo demás. Algunos de tus compañeros también pueden sentir envidia. Tendrás que torear con todo esto. Prepárate y mantén la calma. En el terreno sentimental, una persona o una situación que vivirás, te hará abrir los ojos sobre cómo funciona tu relación. Quizá pienses que no vale la pena esforzarse tanto.')
    break
  case 'cancer':
    case 'Cancer':
    console.log('Muy buena semana en el aspecto económico para las nativas de Cáncer. Empieza un ciclo de prosperidad. La economía está en alza y los proyectos financieros están muy bien aspectados. También podrás salir por fin de esta sensación de no avanzar que te tenía preocupada. Ahora tus proyectos adquieren un nuevo ritmo y esto te va a poner de muy buen humor. Si tienes que echar solicitudes, reclamaciones, demandas… papeleo, ahora te resultará algo más fácil. No lo dejes para más adelante o te arrepentirás. Con la pareja has pasado momentos muy complicados, que te han creado incluso ansiedad pensando que la relación podía irse al traste. Pero está superado y ahora las horas que paséis juntos serán felices, agradables y por la noche habrá mucha pasión. Algunas Cáncer se sentirán atraídas esta semana por una persona de poder. Si estás en este grupo, no te hagas más películas interpretando cada pequeño gesto como un guiño hacia ti. Sólo podrás tener la certeza si te lo dice claramente.')
    break
  case 'leo':
    case 'Leo':
    console.log('Eres muy exigente porque sabes muy bien lo que buscas y lo que quieres, triunfadora Leo. Pero esto no puedes traducirlo en ser demasiado autoritaria en el terreno laboral. Has de encontrar las palabras y el tono para dirigirte a quienes dependen de ti. Habitualmente hablas por igual a los de abajo que a los de arriba, sin embargo, ahora estás tan segura de lo que expresas, que no te paras a pensar que según como lo expongas va a sentar mal. Esto podría generar resentimiento y quizá incluso alguna traición. Tómate las cosas con más calma, aunque te cueste, y si en algún momento la pierdes, que no se te caigan los anillos por disculparte. Te salva tu buen rollo y tu simpatía, pero a veces esta parte negativa puede más. Esta semana evita todo tipo de discusiones con la pareja. Él te demostrará que te quiere y que es muy tolerante, pero no abuses de esto porque puede cansarse. Si notas que te cuesta expresar tus sentimientos escríbele. Una carta a veces hace milagros.')
    break
  case 'virgo':
    case 'Virgo':
    console.log('Entras en una semana genial, Virgo. Ahora te sientes fuerte y esto te hace estar optimista a tope. Esto te dará energía para que puedas realizar todo aquello que vienes deseando desde hace tanto tiempo. Los astros están a tu favor y todo lo que emprendas está destinado al éxito. También será un buen momento para dar pasos de cara a un aumento de salario o tal vez un ascenso que te vendría de perillas. Pero no descuides el humor de quienes te rodean en el ámbito laboral, que no será tan excelente como el tuyo. Esta positividad puede despertar muchas envidias y pueden generar rumores en tu contra. Tenlo en cuenta y protégete, aunque al final quienes quedarán mal serán tus enemigos. Tú conserva la calma y concéntrate porque estás en un momento muy favorable. En el terreno sentimental, serán días propicios a reconciliaciones y declaraciones. Si tienes pareja, evita presionarle para que cambie. Esto sienta mal a cualquiera. Acéptale tal como es. Si estás libre puede surgir ahora una relación apasionada.')
    break
  case 'libra':
    case 'Libra':
    console.log('Durante la pasada semana experimentaste momentos de desaliento en el terreno laboral, Libra, pero esta semana llega un cambio en este campo que te hará sentir más cómoda. La relación con tus compañeros y superiores ahora irá como la seda, incluso puede que inicies una amistad con alguno de tus colegas. Esto supondrá un avance en tu camino profesional, ya que se hablará bien de ti y ganarás prestigio. Si este aspecto funciona bien, puedes dedicar tu energía y esfuerzos al ámbito sentimental. Estás planteándote si la persona que tienes al lado es la adecuada para compartir el presente y hacer planes de futuro. Te gustan de él muchos aspectos, sólo hay algo que te molesta, y es que a veces te hace comentarios sobre tus fallos. Es propio de su personalidad, no lo hace con mala intención y de hecho a ti te beneficia saber en qué puedes mejorar, pero si te sientes herida, tendrás que planteártelo. Si tu corazón anda libre todavía, conocerás a alguien en un lugar de diversión. Esta relación puede consolidarse.')
    break
  case 'escorpion':
    case 'Escorpion':
    console.log('No será precisamente una balsa de aceite esta semana para las nativas de Escorpio. Has pasado una etapa de mucha tensión y te ha desbordado. Como siempre suele ocurrir, puedes explotar en el momento y el lugar menos adecuados, así que pon todo de tu parte para que esto no ocurra. Sé más tolerante, ahora las cosas están cambiando y tu vida se armonizará en todos los aspectos. A veces tus palabras resultan hirientes para tus interlocutores, intenta no ser sarcástica. Si tu corazón está ahora libre, empezarás a tener más ánimo para salir y relacionarte con gente nueva que te puede aportar mucho. En cambio, si tienes pareja, puedes estar pensando en ruptura. Las peleas de los días anteriores te han quitado las ganas de seguir con la relación. No lo hagas, no es momento de tomar estas decisiones. En estos días irás recuperando el buen humor y la crisis de pareja pertenecerá al pasado. Es probable que acabes viendo que él es el hombre de tu vida.')
    break
  case 'sagitario':
    case 'Sagitario':
    console.log('Estás en un magnífico momento para ver con claridad qué personas están sobrando en tu vida, condescendiente Escorpio. Será como cerrar un ciclo e iniciar una nueva etapa. Esta sensación se producirá también en otros los aspectos de tu vida. Deja el pasado atrás, sin dolor ni arrepentimiento, y concéntrate en el presente y en todo lo que de deparará el futuro. Ahora has conseguido la estabilidad económica y te sientes tan bien que estás pensando en aumentar tu capital haciendo algún negocio. Esta semana puede aparecer en tu vida una persona de poder que se interesa por tus proyectos y que está dispuesta a invertir. Deja de temer que el trabajo te falle. No va a suceder, los astros protegen ahora este aspecto, pero si tienes ilusión por crear tu propio proyecto, sigue trabajando en él. En el terreno sentimental, tienes distintos puntos de vista con tu pareja precisamente a causa del dinero. Tú eres más conservadora y él es más de vivir el presente. Esto necesita una solución urgente.')
    break
  case 'capricornio':
    case 'Capricornio':
    console.log('Se avecinan novedades en el campo profesional, luchadora Capricornio. Te harán una propuesta que te entusiasmará y empezarás a pensar en la posibilidad de un cambio. Necesitas tiempo para decidir adecuadamente, no te cortes y pídelo. El interés de quien te ha contactado será aún mayor. Estos días no son adecuados para decisiones, espera un poco. En cambio, esta semana es muy propicia para encontrar la solución a problemas no te dejan dormir. Los astros te favorecen pero eres tú quien debe hacer el esfuerzo por encontrar la salida a estas dificultades. No te quedes parada, esperando. Empieza a actuar y verás como se te abren los caminos para resolverlo. En el terreno sentimental, es una buena etapa para hablar sinceramente con la pareja y expresarle todo lo que sientes. Es cierto que entre vosotros hay momentos de mucha pasión, pero en el día a día siguen las discusiones. Es posible que hayan buenos propósitos por ambas partes, pero tal vez se queden sólo en eso. Espera un poco más y verás las cosas más claras.')
    break
  case 'acuario':
    case 'Acuario':
    console.log('Se te avecina una situación de conflicto en el terreno laboral, nativa de Acuario. Aunque se te haga todo muy cansino, no quieras resolver por la vía fácil este asunto. Es mejor que le dediques tiempo y esfuerzo. Tal vez los resultados no sean para tirar cohetes y no te beneficien, pero tendrás la tranquilidad de que has hecho cuanto estaba en tu mano. Si otra persona se adjudica el mérito, evita sentir envidia hacia ella. La vida nos hace seguir caminos que no entendemos pero que nos llevan siempre a lo mejor para nosotras mismas. Acéptalo tal como viene. En estos días una persona con la que tuviste buena relación en el pasado y se alejó inexplicablemente, volverá a ponerse en contacto. Es una buena oportunidad, trae un proyecto que te ilusiona y es muy importante que se haya acordado de ti. En el terreno sentimental, si estás en pareja, tus dificultades vienen siempre por la falta de comprensión. Ponte en su piel antes de iniciar cualquier discusión, seguro que evitarás muchos roces.')
    break
  case 'picis':
    case 'Picis':
    console.log('Te espera una semana tranquila, Piscis, sin grandes cambios, en el terreno laboral y eso lo que tiene de malo es que puedes ponerte nerviosa porque ciertas cosas que tú desearías que pasaran de inmediato van a tardar todavía unos días en materializarse. No te preocupes porque todo está bien encaminado, sólo que no ha llegado el momento. Aprovecha estos días de calma y recupera tu energía. De hecho no es por el trabajo en sí por lo que estás preocupada, sino por los ingresos que genera. Has pasado tiempo de dificultades económicas y todavía no se han resuelto, por eso estás tan inquieta. Esta semana puedes conocer a una persona clave para salir de una vez por todas de esta situación. Quizá alguien que te ofrezca compartir un negocio que tiene muy buena pinta. Si recientemente has sufrido una ruptura y estabas muy afectada por ello, ahora empiezas a sentirte mejor y a recuperar tu poder de seducción. Te saldrán pretendientes, pero no te precipites y disfruta un tiempo de tu libertad.')
    break
  default:
    console.log('No encontramos su signo sodiacal')
    break
}

